// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt46pPWv_cLVTdqG7zIWEzEkufAHPuCDs',
    appId: '1:323787611914:web:94ee546b3902d5055c64f3',
    messagingSenderId: '323787611914',
    projectId: 'madhw2-db9cb',
    authDomain: 'madhw2-db9cb.firebaseapp.com',
    storageBucket: 'madhw2-db9cb.firebasestorage.app',
    measurementId: 'G-4WC7JS3F22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJsywHCo3XWBTKendkfQ9iv29v2EB-p_c',
    appId: '1:323787611914:android:209091cdbdcba0f35c64f3',
    messagingSenderId: '323787611914',
    projectId: 'madhw2-db9cb',
    storageBucket: 'madhw2-db9cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCisq1qYurSfaQaCUX-pnwa3WKjcUzssfQ',
    appId: '1:323787611914:ios:810349b784d2dc085c64f3',
    messagingSenderId: '323787611914',
    projectId: 'madhw2-db9cb',
    storageBucket: 'madhw2-db9cb.firebasestorage.app',
    iosBundleId: 'com.example.hw2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCisq1qYurSfaQaCUX-pnwa3WKjcUzssfQ',
    appId: '1:323787611914:ios:810349b784d2dc085c64f3',
    messagingSenderId: '323787611914',
    projectId: 'madhw2-db9cb',
    storageBucket: 'madhw2-db9cb.firebasestorage.app',
    iosBundleId: 'com.example.hw2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt46pPWv_cLVTdqG7zIWEzEkufAHPuCDs',
    appId: '1:323787611914:web:e8384a747f61f5c35c64f3',
    messagingSenderId: '323787611914',
    projectId: 'madhw2-db9cb',
    authDomain: 'madhw2-db9cb.firebaseapp.com',
    storageBucket: 'madhw2-db9cb.firebasestorage.app',
    measurementId: 'G-1E3HX3CRRP',
  );
}
